# Mitra configuration file

database_url: postgres://mitra:mitra@127.0.0.1:5432/mitra
storage_dir: /var/lib/mitra

http_host: '127.0.0.1'
http_port: 8383

# Log level (debug, info, warn)
#log_level: info

# Domain name
instance_uri: example.tld
instance_title: example
instance_short_description: my instance
# Long description can contain markdown syntax
instance_description: my instance

registrations_open: false

# EIP-4361 login message
#login_message: 'Do not sign this message on other sites!'

#post_character_limit: 2000

# Blockchain integration
#blockchain:
#  chain_id: eip155:31337
#  contract_address: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9'
#  contract_dir: /usr/share/mitra/contracts
#  api_url: 'http://127.0.0.1:8545'
#  explorer_url: null
#  signing_key: null

# IPFS integration
#ipfs_api_url: 'http://127.0.0.1:5001'
# IPFS gateway (for clients)
#ipfs_gateway_url: 'https://ipfs.example.tld'
