# Mitra configuration file

database_url: postgres://mitra:mitra@127.0.0.1:5432/mitra
storage_dir: /var/lib/mitra
# Path to web client static files
web_client_dir: /usr/share/mitra/www

http_host: '127.0.0.1'
http_port: 8383

# Log level (debug, info, warn)
#log_level: info

# Domain name
instance_uri: example.tld
instance_title: example
instance_short_description: my instance
# Long description can contain markdown syntax
instance_description: my instance

registration:
  # Possible values: open, invite
  type: invite

# EIP-4361 login message
#login_message: 'Do not sign this message on other sites!'

#post_character_limit: 2000

# Proxy for outgoing requests
#proxy_url: 'socks5h://127.0.0.1:9050'

# Limits
#limits:
#  media:
#    file_size_limit: 20M

# List of blocked domains
#blocked_instances: []

# Blockchain integrations
# Multiple configuration are currently not allowed.
# Chain metadata for EVM chains can be found at https://github.com/ethereum-lists/chains
# Signing key for ethereum integration can be generated with `mitractl generate-ethereum-address`
#blockchains:
#  - chain_id: monero:mainnet
#    node_url: 'http://opennode.xmr-tw.org:18089'
#    wallet_url: 'http://127.0.0.1:18083'
#    wallet_name: null
#    wallet_password: null
#  - chain_id: eip155:31337
#    chain_metadata:
#      chain_name: localhost
#      currency_name: ETH
#      currency_symbol: ETH
#      currency_decimals: 18
#      public_api_url: 'http://127.0.0.1:8545'
#      explorer_url: null
#    contract_address: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9'
#    contract_dir: /usr/share/mitra/contracts
#    api_url: 'http://127.0.0.1:8545'
#    signing_key: null
#    chain_sync_step: 1000
#    chain_reorg_max_depth: 10

# IPFS integration
#ipfs_api_url: 'http://127.0.0.1:5001'
# IPFS gateway (for clients)
#ipfs_gateway_url: 'https://ipfs.example.tld'
