# Configuration file for development

database_url: postgres://mitra:mitra@127.0.0.1:55432/mitra
storage_dir: files
web_client_dir: null

http_host: '127.0.0.1'
http_port: 8380

instance_url: http://127.0.0.1:8380

instance_title: Mitra
instance_short_description: My instance
instance_description: My instance
instance_staff_public: true

registration:
  type: open

#blockchains:
#  # Parameters for local Monero node
#  - chain_id: monero:regtest
#    wallet_rpc_url: 'http://127.0.0.1:58083'
#    wallet_rpc_username: null
#    wallet_rpc_password: null
#    wallet_name: test
#    wallet_password: test
#    account_index: 0


#ipfs_api_url: 'http://127.0.0.1:5001'
#ipfs_gateway_url: 'http://127.0.0.1:8001'
