[package]
name = "apx_sdk"
version = "0.1.0"
license.workspace = true

edition.workspace = true
rust-version.workspace = true

[dependencies]
# Used for working with HTTP headers
http = "0.2.9"
# Used for implementing custom DNS resolver
hyper = { version = "0.14.28", default-features = false }
futures-util = { version = "0.3.28", default-features = false }
# Used for logging
log = "0.4.20"
# Used for working with regular expressions
regex = "1.9.6"
# Used for making async HTTP requests
reqwest = { version = "0.11.27", default-features = false, features = ["json", "socks"] }
bytes = "=1.2.0"
# Used for serialization/deserialization
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.89"
# Used for creating error types
thiserror = "1.0.37"

apx_core = { path = "../apx_core" }

[dev-dependencies]
# Async runtime for examples
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }

[features]
default = ["rustls-tls"]

native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls-native-roots"]

[lints]
workspace = true
