CREATE TABLE conversation_tracking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id UUID NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    account_id UUID NOT NULL REFERENCES user_account (id) ON DELETE CASCADE,
    tracking_status SMALLINT NOT NULL,
    UNIQUE (conversation_id, account_id)
);
