#!/bin/bash
### BEGIN INIT INFO
# Provides:          mitra
# Required-Start:    postgresql $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mitra
# Description:       Federated social network
### END INIT INFO

# Author: CaohuaK Ludolf <darkwolf@furmail.cc>

NAME=mitra
DESC="Federated social network"
DAEMON=/usr/bin/mitra
PIDFILE=/run/$NAME.pid
## Change the PATH if your configuration file is not yaml format
export CONFIG_PATH=/etc/$NAME/config.yaml
USER="mitra"
DAEMON_OPTS="server"
LOGFILE=/var/log/mitra.log

test -x $DAEMON || exit 0

. /lib/init/vars.sh
. /lib/lsb/init-functions

start_mitra() {
        start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --exec $DAEMON --chuid "$USER" --background --no-close -- $DAEMON_OPTS >> $LOGFILE 2>&1
        RETVAL="$?"
        return "$RETVAL"
}

stop_mitra() {
        start-stop-daemon --stop --quiet --oknodo --retry=TERM/5/KILL/5 --pidfile $PIDFILE
        RETVAL="$?"
        rm -f $PIDFILE
        return "$RETVAL"
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        start_mitra
        case "$?" in
            0|1) log_end_msg 0 ;;
            2)   log_end_msg 1 ;;
        esac
        ;;

    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        stop_mitra
        case "$?" in
            0|1) log_end_msg 0 ;;
            2)   log_end_msg 1 ;;
        esac
        ;;

    status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;

    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        stop_mitra
        case "$?" in
            0|1)
                start_mitra
                case "$?" in
                    0) log_end_msg 0 ;;
                    1) log_end_msg 1 ;; # Old process is still running
                    *) log_end_msg 1 ;; # Failed to start
                esac
                ;;
            *)
                # Failed to stop
                log_end_msg 1
                ;;
        esac
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}" >&2
        exit 3
        ;;
esac
