[package]
name = "mitra_adapters"
version = "2.10.0"
license = "AGPL-3.0-only"
edition = "2021"
rust-version = "1.63.0"

[dependencies]
# Used for working with dates
chrono = { version = "0.4.23", default-features = false }
# Used for logging
log = "0.4.20"
# Used for working with JSON
serde_json = "1.0.89"
# Async runtime
tokio = { version = "1.28.2", features = ["macros"] }
# Used to work with UUIDs
uuid = "1.1.2"

mitra_config = { path = "../mitra_config" }
mitra_models = { path = "../mitra_models" }
mitra_services = { path = "../mitra_services" }
mitra_validators = { path = "../mitra_validators" }

[dev-dependencies]
serial_test = "0.7.0"

mitra_config = { path = "../mitra_config", features = ["test-utils"] }
mitra_models = { path = "../mitra_models", features = ["test-utils"] }
