when:
  - branch: [main]
    event: [push]

steps:
  build:
    image: docker.io/debian:trixie
    environment:
      DEFAULT_CONFIG_PATH: /etc/mitra/config.yaml
      RUST_VERSION: "1.80.1"
    commands:
      - apt update
      - apt install --yes build-essential musl-tools rustup
      - rustup toolchain install $RUST_VERSION --target x86_64-unknown-linux-musl
      - rustup default $RUST_VERSION
      - cargo build --release --features production --target x86_64-unknown-linux-musl --jobs 4
      - sha256sum ./target/x86_64-unknown-linux-musl/release/mitra
